In [2]:
import torch
# 创建一个 5×3 的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[2.6230e+05, 1.8932e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
import torch
# 创建一个随机初始化的 5*3 矩阵
rand_x = torch.rand(5, 3)
print(rand_x)

tensor([[0.6926, 0.1102, 0.1727],
        [0.6507, 0.8499, 0.5912],
        [0.8212, 0.4162, 0.2538],
        [0.1119, 0.6597, 0.0214],
        [0.9122, 0.9295, 0.0047]])


In [6]:
import torch
# 创建一个数值皆是 0，类型为 long 的矩阵
zero_x = torch.zeros(5, 3, dtype=torch.long)
print(zero_x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
import torch
# 直接用列表创建
tensor1 = torch.tensor([5.5, 3])
print(tensor1)

# 二维列表
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)

tensor([5.5000, 3.0000])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [12]:
import torch
tensor1 = torch.tensor([5.5, 3])
print(tensor1)
# 显示定义新的尺寸是 5*3，数值类型是 torch.double
  # new_* 方法需要输入 tensor 大小
tensor3 = tensor1.new_ones(5, 3, dtype=torch.double)
print(tensor3)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
import torch
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)
# 修改数值类型
tensor4 = torch.randn_like(tensor2, dtype=torch.float)
print(tensor4)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1.2256,  0.8793, -1.2986],
        [-1.0772, -0.4383, -0.7421],
        [-0.7059,  1.0707,  0.8640]])


In [15]:
import torch
tensor5 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor5.size()) 

torch.Size([3, 3])


In [20]:
import torch 
tensor6 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
tensor7 = torch.rand(3, 3)

print('+运算符')
print(tensor6 + tensor7)
print('torch.add(tensor1, tensor2, [out=tensor3])')
# 声明一个 3×3 的未初始化的矩阵，用于保存加法操作结果
tensor8 = torch.empty(3, 3)
print(torch.add(tensor6, tensor7, out=tensor8))
print(tensor8)
# 直接修改变量
print('tensor1.add_(tensor2)')
print(tensor6.add_(tensor7))
print(tensor6)

+运算符
tensor([[1.6342, 2.9043, 3.2132],
        [4.7699, 5.4462, 6.2296],
        [7.9417, 8.6639, 9.8168]], dtype=torch.float64)
torch.add(tensor1, tensor2, [out=tensor3])
tensor([[1.6342, 2.9043, 3.2132],
        [4.7699, 5.4462, 6.2296],
        [7.9417, 8.6639, 9.8168]])
tensor([[1.6342, 2.9043, 3.2132],
        [4.7699, 5.4462, 6.2296],
        [7.9417, 8.6639, 9.8168]])
tensor1.add_(tensor2)
tensor([[1.6342, 2.9043, 3.2132],
        [4.7699, 5.4462, 6.2296],
        [7.9417, 8.6639, 9.8168]], dtype=torch.float64)
tensor([[1.6342, 2.9043, 3.2132],
        [4.7699, 5.4462, 6.2296],
        [7.9417, 8.6639, 9.8168]], dtype=torch.float64)


In [24]:
import torch
tensor9 = torch.rand(5, 4)
print(tensor9)
# 访问 tensor9 第一列数据
print(tensor9[:, 0])
# 访问 tensor9 第2-4行数据
print(tensor9[1:4, :])

tensor([[0.1671, 0.2738, 0.9056, 0.3052],
        [0.8883, 0.0234, 0.9751, 0.5849],
        [0.3800, 0.9318, 0.1067, 0.2627],
        [0.5814, 0.3606, 0.2599, 0.1000],
        [0.9681, 0.5262, 0.9840, 0.3978]])
tensor([0.1671, 0.8883, 0.3800, 0.5814, 0.9681])
tensor([[0.8883, 0.0234, 0.9751, 0.5849],
        [0.3800, 0.9318, 0.1067, 0.2627],
        [0.5814, 0.3606, 0.2599, 0.1000]])


In [27]:
x = torch.randn(4, 4)
y = x.view(16)
# -1 表示除给定维度外的其余维度的乘积
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
import torch
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7281])
0.728061854839325


In [30]:
import torch 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [31]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA 张量

In [33]:
# 当 CUDA 可用的时候，可用运行下方这段代码，采用 torch.device() 方法来改变 tensors 是否在 GPU 上进行计算操作
if torch.cuda.is_available():
    device = torch.device("cuda")          # 定义一个 CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 显示创建在 GPU 上的一个 tensor
    x = x.to(device)                       # 也可以采用 .to("cuda") 
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # .to() 方法也可以改变数值类型

tensor([1.7281], device='cuda:0')
tensor([1.7281], dtype=torch.float64)


## autograd

In [34]:
import torch 
# 开始创建一个 tensor， 并设置 requires_grad=True 来追踪该变量相关的计算操作：
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [35]:
# 执行任意计算操作，这里进行简单的加法运算：
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [36]:
# y 是一个操作的结果，所以它带有属性 grad_fn：
print(y.grad_fn)

In [37]:
# 继续对变量 y 进行操作：
z = y * y * 3
out = z.mean()
print('z=', z)
print('out=', out)

z= tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
out= tensor(27., grad_fn=<MeanBackward0>)


In [38]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [39]:
out.backward()
# 输出梯度 d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [43]:
x = torch.randn(3, requires_grad=True)

y = x * 2
# tensor1.data：返回一个和 tensor1 有着相同数据的 tensor，且返回的新 tensor 与 tensor1 共享同一个内存空间
# tensor.data.norm()：它对张量y每个元素进行平方，然后对它们求和，最后取平方根。 这些操作计算就是所谓的L2或欧几里德范数 
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 152.5833,  684.7393, -792.4349], grad_fn=<MulBackward0>)


In [44]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [45]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


## 神经网络

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 输入图像是单通道，conv1 kenrnel size=5*5，输出通道 6
        self.conv1 = nn.Conv2d(1, 6, 5)
        # conv2 kernel size=5*5, 输出通道 16
        self.conv2 = nn.Conv2d(6, 16, 5)
        # 全连接层
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # max-pooling 采用一个 (2,2) 的滑动窗口
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # 核(kernel)大小是方形的话，可仅定义一个数字，如 (2,2) 用 2 即可
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        # 除了 batch 维度外的所有维度
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
# 打印网络结构
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
params = list(net.parameters())
print('参数数量: ', len(params))
# conv1.weight
print('第一个参数大小: ', params[0].size())

参数数量:  10
第一个参数大小:  torch.Size([6, 1, 5, 5])


In [3]:
# 随机定义一个变量输入网络
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0475,  0.1172,  0.0313, -0.1010,  0.0285,  0.1629,  0.0408, -0.0386,
          0.0118,  0.1917]], grad_fn=<AddmmBackward0>)


In [4]:
# 清空所有参数的梯度缓存，然后计算随机梯度进行反向传播
net.zero_grad()
out.backward(torch.randn(1, 10))

In [5]:
output = net(input)
# 定义伪标签
target = torch.randn(10)
# 调整大小，使得和 output 一样的 size
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.2155, grad_fn=<MseLossBackward0>)


In [6]:
# MSELoss
print(loss.grad_fn)
# Linear layer
print(loss.grad_fn.next_functions[0][0])
# Relu
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [7]:
# 清空所有参数的梯度缓存
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([ 0.0171,  0.0008, -0.0021,  0.0232, -0.0166, -0.0029])
