In [2]:
import torch
# 创建一个 5×3 的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[2.6230e+05, 1.8932e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [2]:
import torch
# 创建一个随机初始化的 5*3 矩阵
rand_x = torch.rand(5, 3)
print(rand_x)
print(rand_x.type())

tensor([[0.7603, 0.9944, 0.1590],
        [0.7834, 0.0624, 0.1872],
        [0.5408, 0.6831, 0.7307],
        [0.7364, 0.4590, 0.5095],
        [0.1685, 0.0814, 0.1444]])
torch.FloatTensor


In [6]:
import torch
# 创建一个数值皆是 0，类型为 long 的矩阵
zero_x = torch.zeros(5, 3, dtype=torch.long)
print(zero_x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
import torch
# 直接用列表创建
tensor1 = torch.tensor([5.5, 3])
print(tensor1)

# 二维列表
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)

tensor([5.5000, 3.0000])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [12]:
import torch
tensor1 = torch.tensor([5.5, 3])
print(tensor1)
# 显示定义新的尺寸是 5*3，数值类型是 torch.double
  # new_* 方法需要输入 tensor 大小
tensor3 = tensor1.new_ones(5, 3, dtype=torch.double)
print(tensor3)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [1]:
import torch
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)
# 修改数值类型
tensor4 = torch.randn_like(tensor2, dtype=torch.float)
print(tensor4)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 0.0905, -0.8127,  1.2278],
        [ 0.8381,  0.2935,  0.0379],
        [-0.2319, -0.5507, -0.9525]])


In [7]:
# 如果不用列表，之间用数值创建，则 tensor 是 0 维的标量
x = torch.tensor(1)
print(x.size())
print(x.dim())
# 如果使用了列表创建 tensor ，则列表与 tensor 维度相同（向量）
y = torch.tensor([1])
print(y.size())
print(y.dim())

torch.Size([])
0
torch.Size([1])
1
