### torch.empty()：声明一个未初始化的矩阵

In [2]:
import torch
# 创建一个 5×3 的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[2.6230e+05, 1.8932e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


### torch.rand()：随机初始化一个矩阵

In [2]:
import torch
# 创建一个随机初始化的 5*3 矩阵
rand_x = torch.rand(5, 3)
print(rand_x)
print(rand_x.type())

tensor([[0.7603, 0.9944, 0.1590],
        [0.7834, 0.0624, 0.1872],
        [0.5408, 0.6831, 0.7307],
        [0.7364, 0.4590, 0.5095],
        [0.1685, 0.0814, 0.1444]])
torch.FloatTensor


### torch.randint()：随机初始化一个矩阵（指定随机数的取值范围）

In [9]:
import torch
# 前两个参数指定了随机数的取值范围为：[1, 10)
# 第三个参数指定 tensor 的 shape
x = torch.randint(1, 10, [3, 3])
print(x)

tensor([[5, 3, 1],
        [3, 7, 5],
        [8, 6, 8]])


### torch.randn()：随机初始化一个矩阵（数值服从正态分布N(0, 1)）

In [11]:
import torch 
# 生成一个 shape 为 (3, 3) 的随机矩阵，数值服从正态分布 N(0, 1)
x = torch.randn(3, 3)
print(x)


tensor([[ 0.3734, -0.3038,  1.7177],
        [-0.4694,  1.8895,  0.2481],
        [ 0.0937,  0.5411,  0.1127]])


### torch.normal()：返回从单独的正态分布中提取的随机数的张量

In [12]:
import torch
# 从一个标准正态分布N～(0,1)，提取一个2x2的矩阵
x = torch.normal(mean=0.,std=1.,size=(2,2))
print(x)

# 也可以让每一个值服从不同的正态分布，我们还是生成2x2的矩阵
y = torch.normal(mean=torch.arange(4.),std=torch.arange(1.,0.6,-0.1)).reshape(2,2)
print(y)

tensor([[1.6425, 2.0073],
        [0.5646, 0.0795]])
tensor([[-0.8937, -0.1693],
        [ 1.2633,  3.8531]])


### torch.zeros()、torch.ones()、torch.eye()：创建数值皆为 0、1 的矩阵

In [20]:
import torch
# 创建一个数值皆是 0，类型为 long 的矩阵
zero_x = torch.zeros(5, 3, dtype=torch.long)
print(zero_x)

# 创建一个数值皆是 1
one_x = torch.ones(3, 3)
print(one_x)

# 创建一个主对角线全为 1，其余均为 0 的矩阵
eye_x = torch.eye(3, 4)
print(eye_x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


### torch.full()：创建一个数值都一样的矩阵

In [13]:
import torch 
# 创建一个 shape 为 (2, 3)，数值都为 7 的矩阵
x = torch.full([2, 3], 7)
print(x)
# 创建一个维度为 0，数值为 7 的标量
x = torch.full([], 7)
print(x)
# 创建一个维度为 1，数值为 7 的矩阵
x = torch.full([1], 7)
print(x)

tensor([[7, 7, 7],
        [7, 7, 7]])
tensor(7)
tensor([7])


### torch.arange()：创建一个数值为等差数列的矩阵

In [14]:
import torch
# 创建一个数值为 1-10（不包括10）的矩阵
x = torch.arange(1, 10)
print(x)

# 创建一个数值为 1-10（不包括10）且公差（步长）为 2 的矩阵
x = torch.arange(1, 10, 2)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])


### torch.linspace()、torch.logspace()：创建一个指定元素个数的矩阵

In [17]:
import torch 
# 创建一个数值从 0 到 10 均匀分布，元素个数为 4 的矩阵
x = torch.linspace(0, 10, steps=4)
print(x)

# 创建一个数值从 0 到 10（不包括10）均匀分布，元素个数为 10 的矩阵
x = torch.linspace(0, 10, steps=10)
print(x)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [18]:
# 创建一个数值从 10^0 到 10^-1 均匀分布，元素个数为 10 的矩阵
x = torch.logspace(0, -1, 10)
print(x)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])


### torch.randperm(n)：创建一个 0~n（不包括n）随机打乱后获得的数字序列

In [22]:
import torch
# 0 到 10（不包括10）且顺序打乱的数字序列
x = torch.randperm(10)
print(x)

tensor([6, 2, 3, 7, 0, 1, 5, 9, 8, 4])


### torch.tensor()：直接传递数值来创建

In [11]:
import torch
# 直接用列表创建
tensor1 = torch.tensor([5.5, 3])
print(tensor1)

# 二维列表
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)

tensor([5.5000, 3.0000])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [7]:
# 如果不用列表，之间用数值创建，则 tensor 是 0 维的标量
x = torch.tensor(1)
print(x.size())
print(x.dim())
# 如果使用了列表创建 tensor ，则列表与 tensor 维度相同（向量）
y = torch.tensor([1])
print(y.size())
print(y.dim())

torch.Size([])
0
torch.Size([1])
1


In [8]:
import torch
x = torch.tensor(3)
print(x)
y = torch.Tensor(3)
print(y)

tensor(3)
tensor([0., 0., 0.])


### tensor.new_ones()：根据已有的 tensor 变量创建新的数值为1的 tensor 变量

In [12]:
import torch
tensor1 = torch.tensor([5.5, 3])
print(tensor1)
# 显示定义新的尺寸是 5*3，数值类型是 torch.double
  # new_* 方法需要输入 tensor 大小
tensor3 = tensor1.new_ones(5, 3, dtype=torch.double)
print(tensor3)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### torch.rand_like(old_tensor)：保留相同的尺寸大小

In [1]:
import torch
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)
# 修改数值类型
tensor4 = torch.randn_like(tensor2, dtype=torch.float)
print(tensor4)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 0.0905, -0.8127,  1.2278],
        [ 0.8381,  0.2935,  0.0379],
        [-0.2319, -0.5507, -0.9525]])
