## operations

### 加法操作

In [1]:
import torch 
tensor6 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
tensor7 = torch.rand(3, 3)

print('+运算符')
print(tensor6 + tensor7)
print('torch.add(tensor1, tensor2, [out=tensor3])')
# 声明一个 3×3 的未初始化的矩阵，用于保存加法操作结果
tensor8 = torch.empty(3, 3)
print(torch.add(tensor6, tensor7, out=tensor8))
print(tensor8)
# 直接修改变量
print('tensor1.add_(tensor2)')
print(tensor6.add_(tensor7))
print(tensor6)

+运算符
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)
torch.add(tensor1, tensor2, [out=tensor3])
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]])
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]])
tensor1.add_(tensor2)
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)


### 索引、切片

In [2]:
import torch
tensor9 = torch.rand(5, 4)
print(tensor9)
# 访问 tensor9 第一列数据
print(tensor9[:, 0])
# 访问 tensor9 第2-4行数据
print(tensor9[1:4, :])

tensor([[0.8344, 0.7298, 0.1510, 0.9846],
        [0.6693, 0.1510, 0.6123, 0.7776],
        [0.0400, 0.9036, 0.6243, 0.6570],
        [0.9421, 0.5009, 0.6743, 0.3254],
        [0.1927, 0.9144, 0.7907, 0.9714]])
tensor([0.8344, 0.6693, 0.0400, 0.9421, 0.1927])
tensor([[0.6693, 0.1510, 0.6123, 0.7776],
        [0.0400, 0.9036, 0.6243, 0.6570],
        [0.9421, 0.5009, 0.6743, 0.3254]])


### tensor.size()：获取 tensor 的尺寸

In [14]:
import torch
tensor5 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor5.size()) 
print(tensor5.shape)

torch.Size([3, 3])
torch.Size([3, 3])


### tensor.view()：修改 tensor 尺寸

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
# -1 表示除给定维度外的其余维度的乘积
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### tensor.item()：获取数值

In [ ]:
import torch
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7281])
0.728061854839325


### tensor.type()：获取 tensor 的类型

In [13]:
import torch
x = torch.tensor(3.1)
print(x)
print(x.type())
print(type(x))
print(x.dim())

y = torch.tensor([3.1])
print(y)
print(y.dim())


tensor(3.1000)
torch.FloatTensor
<class 'torch.Tensor'>
0
tensor([3.1000])
1


### isinstance(a, b)：检查 a 是否为 类型 b

In [11]:
print(isinstance(x, torch.FloatTensor))
print(isinstance(x, torch.IntTensor))

print(isinstance(x, torch.cuda.FloatTensor))
# tensor.cuda()：返回一个GPU上的引用
x = x.cuda()
print(isinstance(x, torch.cuda.FloatTensor))

True
False
False
True
