## operations

### tensor.item()：获取数值

In [ ]:
import torch
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3251])
1.3250837326049805


### isinstance(a, b)：检查 a 是否为 类型 b

In [ ]:
print(isinstance(x, torch.FloatTensor))
print(isinstance(x, torch.IntTensor))

print(isinstance(x, torch.cuda.FloatTensor))
# tensor.cuda()：返回一个GPU上的引用
x = x.cuda()
print(isinstance(x, torch.cuda.FloatTensor))

True
False
False
True


### tensor.type()：获取 tensor 的类型

In [ ]:
import torch
x = torch.tensor(3.1)
print(x)
print(x.type())
print(type(x))
print(x.dim())

y = torch.tensor([3.1])
print(y)
print(y.dim())


tensor(3.1000)
torch.FloatTensor
<class 'torch.Tensor'>
0
tensor([3.1000])
1


### 加法操作

In [1]:
import torch 
tensor6 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
tensor7 = torch.rand(3, 3)

print('+运算符')
print(tensor6 + tensor7)
print('torch.add(tensor1, tensor2, [out=tensor3])')
# 声明一个 3×3 的未初始化的矩阵，用于保存加法操作结果
tensor8 = torch.empty(3, 3)
print(torch.add(tensor6, tensor7, out=tensor8))
print(tensor8)
# 直接修改变量
print('tensor1.add_(tensor2)')
print(tensor6.add_(tensor7))
print(tensor6)

+运算符
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)
torch.add(tensor1, tensor2, [out=tensor3])
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]])
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]])
tensor1.add_(tensor2)
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)
tensor([[1.9848, 2.1800, 3.7232],
        [4.9318, 5.7457, 6.7742],
        [7.0447, 8.2947, 9.0247]], dtype=torch.float64)


### 索引、切片

In [3]:
import torch
a = torch.rand(4, 3, 28, 28)
print(a[0].shape)
print(a[0, 0].shape)
print(a[0, 0, 2, 4])

torch.Size([3, 28, 28])
torch.Size([28, 28])
tensor(0.0072)


In [2]:
import torch
tensor9 = torch.rand(5, 4)
print(tensor9)
# 访问 tensor9 第一列数据
print(tensor9[:, 0])
# 访问 tensor9 第2-4行数据
print(tensor9[1:4, :])

tensor([[0.0123, 0.4111, 0.2937, 0.6465],
        [0.2768, 0.0355, 0.8906, 0.8671],
        [0.0767, 0.7646, 0.1118, 0.6093],
        [0.5245, 0.7564, 0.6740, 0.9658],
        [0.7562, 0.4768, 0.7117, 0.6085]])
tensor([0.0123, 0.2768, 0.0767, 0.5245, 0.7562])
tensor([[0.2768, 0.0355, 0.8906, 0.8671],
        [0.0767, 0.7646, 0.1118, 0.6093],
        [0.5245, 0.7564, 0.6740, 0.9658]])


### tensor.size()：获取 tensor 的尺寸

In [14]:
import torch
tensor5 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor5.size()) 
print(tensor5.shape)

torch.Size([3, 3])
torch.Size([3, 3])


### tensor.view()、tensor.reshape()：修改 tensor 尺寸

In [4]:
x = torch.randn(4, 4)
y = x.view(16)
# -1 表示除给定维度外的其余维度的乘积
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

y2 = x.reshape(16)
z2 = x.reshape(-1, 8)
print(x.size(), y2.size(), z2.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### tensor.unsqueeze()、tensor.squeeze()：为 tensor 插入/删除维度

In [8]:
import torch
a = torch.rand(4, 1, 28, 28)
print(a.shape)

# 在第 0 个维度前面插入一个维度
b = a.unsqueeze(0)
print(b.shape)

# 在倒数第 1 个维度后面插入一个维度
c = a.unsqueeze(-1)
print(c.shape)

torch.Size([4, 1, 28, 28])
torch.Size([1, 4, 1, 28, 28])
torch.Size([4, 1, 28, 28, 1])


In [25]:
import torch
a = torch.rand(1, 32, 1, 2, 1, 1)
print(a.shape)

# 删减索引为2的维度
b = a.squeeze(2)
print(b.shape)

# 删减索引为-6的维度
c = a.squeeze(-6)
print(c.shape)

# 删减所有维度为1的维度
d = a.squeeze()
print(d.shape)

# 注意：不是1维的维度是不能被删除的
print(a.squeeze(1).shape)
print(a.squeeze(-3).shape)

torch.Size([1, 32, 1, 2, 1, 1])
torch.Size([1, 32, 2, 1, 1])
torch.Size([32, 1, 2, 1, 1])
torch.Size([32, 2])
torch.Size([1, 32, 1, 2, 1, 1])
torch.Size([1, 32, 1, 2, 1, 1])


### tensor.expand()、tensor.repeat()：维度扩展

In [29]:
import torch
a = torch.rand(1, 32, 1, 1)
print(a.shape)

b = a.expand(2, 32, 3, 3)
print(b.shape)

# 不进行扩展（或不能扩展）的维度可用-1代替
c = a.expand(-1, -1, 10, 10)
print(c.shape)

torch.Size([1, 32, 1, 1])
torch.Size([2, 32, 3, 3])
torch.Size([1, 32, 10, 10])


In [34]:
import torch
a = torch.rand(1, 32, 1, 1)
print(a.shape)

b = a.repeat(2, 2, 3, 3)
print(b.shape)

# 不需要进行重复的维度用1
c = a.repeat(2, 1, 3, 3)
print(c.shape)

torch.Size([1, 32, 1, 1])
torch.Size([2, 64, 3, 3])
torch.Size([2, 32, 3, 3])


### tensor.t()：二维矩阵转置操作

转置操作只能用于二维矩阵，否则会报错

In [7]:
import torch 
a = torch.randint(1, 10, [4, 4])
print(a)
print(a.t())

tensor([[3, 2, 1, 9],
        [8, 4, 6, 4],
        [1, 3, 6, 9],
        [3, 4, 8, 2]])
tensor([[3, 8, 1, 3],
        [2, 4, 3, 4],
        [1, 6, 6, 8],
        [9, 4, 9, 2]])


### tensor.transpose()：维度交换操作

In [9]:
import torch 
a = torch.randint(1, 10, [3, 4, 32])
print(a.shape)
# 交换索引维0和索引为2的两个维度
b = a.transpose(0, 2)
print(b.shape)

torch.Size([3, 4, 32])
torch.Size([32, 4, 3])


### tensor.permute()：将tensor的维度换位

In [12]:
import torch 
a = torch.randint(1, 10, [3, 4, 32, 24])
# a 的第 0 个位置的维度为 3
#   第 1 个位置维度为 4
#   第 2 个位置维度为 32
#   第 3 个位置维度为32
print(a.shape)

# 将原本维度的位置，按 0, 3, 1, 2 的顺序重排放
b = a.permute(0, 3, 1, 2)
print(b.shape)

torch.Size([3, 4, 32, 24])
torch.Size([3, 24, 4, 32])
