### Tensor 转换为 Numpy 数组

调用 tensor.numpy() 可以实现 Tensor 转换为 Numpy 数组

In [ ]:
import torch 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


两者是共享同个内存空间的，例子如下所示，修改 tensor 变量 a，a 转换得到的 Numpy 数组变量 b 也会发生变化

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy 数组转换为 Tensor

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
