### 矩阵相乘
1. torch.matmul
2. @

In [5]:
import torch
a = torch.ones(2, 2)
b = torch.full([2, 2], 3, dtype=torch.float)
print(a)
print(b)
print(a@b)
print(torch.matmul(a, b))


tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[6., 6.],
        [6., 6.]])
tensor([[6., 6.],
        [6., 6.]])


In [12]:
import torch 
# 高于2维的矩阵进行矩阵相乘时，只对后面两维进行矩阵相乘，而除了后两维外，其余维度要保持一致
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)
print((a@b).shape)

torch.Size([4, 3, 28, 32])


### tensor.pow(n)：n次方、tensor.sqrt()：平方根

In [18]:
import torch 
a = torch.full([2, 2], 3)
print(a)
# 2 次方
b = a.pow(2)
c = a ** 2
print(b)

print(c)

# 平方根 3
print(c.sqrt())

# 平方根的倒数 1/3
print(c.rsqrt())

tensor([[3, 3],
        [3, 3]])
tensor([[9, 9],
        [9, 9]])
tensor([[9, 9],
        [9, 9]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])


### torch.exp()、torch.log()

In [21]:
import torch 
a = torch.full([2, 2], 1)
# e^1 = 2.71
b = torch.exp(a)
print(b)

a.add_(1)
# e^2 = 7.38
c = torch.exp(a)
print(c)

# log 默认以 e 为底
# 以 2 为底的函数为 log2，同理有 log10
d = torch.log(b)
e = torch.log(c)
print(d)
print(e)

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[7.3891, 7.3891],
        [7.3891, 7.3891]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


### 近似值（向上取整、向下取整、取整数部分、取小数部分、四舍五入）

In [23]:
import torch 
a = torch.tensor(3.14)
# 近似值（向上取整、向下取整、取整数部分、取小数部分）
print(a.ceil(), a.floor(), a.trunc(), a.frac())

# 四舍五入
b = torch.tensor(3.499)
c = torch.tensor(3.511)
print(b.round(), c.round())

tensor(4.) tensor(3.) tensor(3.) tensor(0.1400)
tensor(3.) tensor(4.)


### tensor.clamp()：限幅

In [28]:
import torch
grand = torch.randn(2, 3) * 15
print(grand)

# 把最小值限制为 10，低于 10 的数值用 10 替换
grand = grand.clamp(10)
print(grand)

grand2 = torch.randn(2, 3) * 15
print(grand2)

# 把最小值限制为 10，低于 10 的数值用 10 替换
# 限制最大值为 20，大于 20 的数值用 20 替换
grand2 = grand2.clamp(10, 20)
print(grand2)

tensor([[  5.5845,  -1.0966,   2.7625],
        [ 27.1874,  -9.9242, -21.6876]])
tensor([[10.0000, 10.0000, 10.0000],
        [27.1874, 10.0000, 10.0000]])
tensor([[-10.2177, -18.6620,  15.3624],
        [ 25.0338, -16.3466,   0.7395]])
tensor([[10.0000, 10.0000, 15.3624],
        [20.0000, 10.0000, 10.0000]])
