### tensor.norm 求范数

In [10]:
import torch 
a = torch.full([8], 1, dtype=torch.float)

b = a.view(2, 4)
c = a.view(2, 2, 2)

# l-1 范数
print(a.norm(1), b.norm(1), c.norm(1))

# l-2 范数
print(a.norm(2), b.norm(2), c.norm(2))

# 在指定维度上求 l-1 范数
print(b.norm(1, dim=1))
# 在指定维度上求 l-2 范数
print(c.norm(2, dim=1))

tensor(8.) tensor(8.) tensor(8.)
tensor(2.8284) tensor(2.8284) tensor(2.8284)
tensor([4., 4.])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


### .min .max .mean .prod .sum 求最小值、最大值、平均值、累乘值、累加值

In [24]:
import torch
a = torch.randperm(8).view(2, 2, 2).float()
print(a)
print(a.min(), a.max(), a.mean(), a.prod(), a.sum())
print(a.argmin(), a.argmax())
print(a.argmin(dim=2))

tensor([[[7., 2.],
         [0., 4.]],

        [[1., 5.],
         [6., 3.]]])
tensor(0.) tensor(7.) tensor(3.5000) tensor(0.) tensor(28.)
tensor(2) tensor(0)
tensor([[1, 0],
        [0, 1]])


### dim、keepdim 参数

In [9]:
import torch
a = torch.randperm(40).view(4, 10).float()
print(a)
print(a.max(dim=1))
print(a.argmax(dim=1))

print(a.max(dim=1, keepdim=True))
print(a.argmax(dim=1, keepdim=True))

tensor([[11., 37.,  2.,  6., 22., 30.,  8., 29., 14., 38.],
        [13., 20., 12., 33., 15.,  7., 21.,  0.,  9., 26.],
        [39., 35., 36., 34.,  5., 27., 32.,  3., 19., 18.],
        [23., 24.,  4., 28., 16., 31., 10., 25., 17.,  1.]])
torch.return_types.max(
values=tensor([38., 33., 39., 31.]),
indices=tensor([9, 3, 0, 5]))
tensor([9, 3, 0, 5])
torch.return_types.max(
values=tensor([[38.],
        [33.],
        [39.],
        [31.]]),
indices=tensor([[9],
        [3],
        [0],
        [5]]))
tensor([[9],
        [3],
        [0],
        [5]])


### tensor.topk(k)：取数值大小排前 k 名的数值

In [13]:
import torch
a = torch.randperm(40).view(4, 10).float()
print(a)
# 取数值大小排前 k 名的数值（最大 k 个数）
print(a.topk(3, dim=1))

# 取数值大小排后 k 名的数值（最小 k 个数）
print(a.topk(3, dim=1, largest=False))

tensor([[38.,  7., 16., 29., 21., 31.,  5., 36.,  1., 24.],
        [18., 13., 39., 22.,  8., 37., 11., 17., 33.,  6.],
        [23., 25., 34., 30., 14.,  0., 19., 12., 27., 15.],
        [20.,  9., 35., 26.,  3.,  4., 10., 28.,  2., 32.]])
torch.return_types.topk(
values=tensor([[38., 36., 31.],
        [39., 37., 33.],
        [34., 30., 27.],
        [35., 32., 28.]]),
indices=tensor([[0, 7, 5],
        [2, 5, 8],
        [2, 3, 8],
        [2, 9, 7]]))
torch.return_types.topk(
values=tensor([[ 1.,  5.,  7.],
        [ 6.,  8., 11.],
        [ 0., 12., 14.],
        [ 2.,  3.,  4.]]),
indices=tensor([[8, 6, 1],
        [9, 4, 6],
        [5, 7, 4],
        [8, 4, 5]]))


### tensor.kthvalue(k)：取数值排在第 k 小的数值

In [3]:
import torch
a = torch.randperm(40).view(4, 10).float()
print(a)
# 在指定维度上取排在第 3 小的数值
print(a.kthvalue(3, dim=1))

tensor([[32.,  6., 26., 37., 21., 28.,  1., 24., 25., 35.],
        [15.,  5., 39., 18.,  3., 12.,  7., 30.,  9., 10.],
        [31., 38., 13.,  0., 11.,  4., 22.,  2., 14., 20.],
        [27., 33., 29., 34., 19., 16.,  8., 23., 36., 17.]])
torch.return_types.kthvalue(
values=tensor([21.,  7.,  4., 17.]),
indices=tensor([4, 6, 5, 9]))


### 比较：>、>=、<、<=、!=、==

In [10]:
import torch
a = torch.randperm(40).view(4, 10).float()
print(a)

# tensor 中大于 5 的数值
print(a>5)
print(torch.gt(a, 5))

# tensor 中等于 6 的数值
print(a==6)
print(torch.eq(a, 6))

print(a==a)
print(torch.eq(a, a))

print(torch.equal(a, a))

tensor([[ 4.,  6., 34., 35.,  1., 37.,  5., 10., 38., 14.],
        [17., 18., 39., 25.,  0., 27., 28.,  9.,  7., 15.],
        [13.,  8., 20., 24., 11., 19., 22., 30., 31., 12.],
        [29., 23., 36., 26., 33.,  2., 16.,  3., 21., 32.]])
tensor([[False,  True,  True,  True, False,  True, False,  True,  True,  True],
        [ True,  True,  True,  True, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True, False,  True, False,  True,  True]])
tensor([[False,  True,  True,  True, False,  True, False,  True,  True,  True],
        [ True,  True,  True,  True, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True, False,  True, False,  True,  True]])
tensor([[False,  True, False, False, False, False, False, False, False, False],
        [False, False, False, False, 