### torch.where()

torch.where(condition, x, y) -> Tensor

Return a  tensor of elements selected from either x or y, depending on condition.

In [18]:
import torch
cond = torch.randn(2, 2)
print(cond)

a = torch.zeros(2, 2)
b = torch.ones(2, 2)
print(a)
print(b)

# 矩阵 c 由矩阵 a 和矩阵 b 的部分元素组成
# 当 cond[i, j] > 0.5 时，c[i, j] = a[i, j]，否则 c[i, j] = b[i, j]
c = torch.where(cond>0.5, a, b)
print(c)

tensor([[ 1.2192,  1.2888],
        [ 0.3824, -0.0944]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [1., 1.]])


### torch.gather()

torch.gather(input, dim, index, out=None) -> Tensor

Gathers values along an axis specified by dim

In [21]:
import torch 
prob = torch.randn(4, 10)
index = prob.topk(dim=1, k=3)
print(index)
index = index[1]
print(index)

label = torch.arange(10) + 100
print(label)
print(label.expand(4, 10))

out = torch.gather(label.expand(4, 10), dim=1, index=index.long())
print(out)

torch.return_types.topk(
values=tensor([[2.3710, 1.9753, 0.2838],
        [1.4316, 0.8431, 0.6633],
        [1.8113, 1.3453, 1.0668],
        [2.3601, 1.3609, 0.7615]]),
indices=tensor([[1, 8, 2],
        [7, 9, 2],
        [8, 0, 1],
        [2, 5, 7]]))
tensor([[1, 8, 2],
        [7, 9, 2],
        [8, 0, 1],
        [2, 5, 7]])
tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])
tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])
tensor([[101, 108, 102],
        [107, 109, 102],
        [108, 100, 101],
        [102, 105, 107]])
