### sigmoid 函数

sigmoid 函数：$S\left ( x \right )  = \frac{e^x}{e^x+1}$

sigmoid 函数导数：$S'\left ( x \right )  = S(x)\left ( 1-S(x) \right ) $

<img src="./assets/sigmoid.png" alt="sigmoid 函数" width=650 height=400/>

In [4]:
import torch
from torch.nn import functional as F

z = torch.linspace(-100, 100, 10)
print(z)

print(torch.sigmoid(z))
print(F.sigmoid(z))

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5556,   77.7778,  100.0000])
tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])
tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])


### tanh 函数

$f(x) = tanh(x) = \frac{e^x-\frac{1}{e^x}  }{e^x+\frac{1}{e^x}} =2sigmoid(2x)-1$

f'(x) = tanh'(x) = 1-tanh^2(x)

<img src="./assets/tanh.png" alt="tanh 函数" width=650 height=400/>

In [5]:
import torch 
z = torch.linspace(-1, 1, 10)
print(z)

print(torch.tanh(z))

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])
tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])


### ReLU 函数

<img src="./assets/ReLU.png" alt="relu 函数" width=1000 height=350/>

In [6]:
import torch
from torch.nn import functional as F

z = torch.linspace(-1, 1, 10)
print(z)

print(torch.relu(z))
print(F.relu(z))

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])
